In [1]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))

1
3
4
6
7
12
13
18
8
34
[ 1  3  4  6  7  8 12 13 18 34]


In [4]:
arr=np.array([1,2,3,4,5,6,5,3])
print(arr.ndim)
print(arr.size)

1
8


In [5]:
arr=np.array([1,2,3,4,5,6])
t=arr
t=t[:, np.newaxis]
print(t)
print(arr)
t=arr
t=np.expand_dims(t,2)
print(t)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


AxisError: axis 2 is out of bounds for array of dimension 2

In [6]:
a=np.array([[11,22,32],[4,5,64],[77,18,29]])
print(np.vstack(a))
print(np.hstack(a))

[[11 22 32]
 [ 4  5 64]
 [77 18 29]]
[11 22 32  4  5 64 77 18 29]


In [8]:

a=np.arange(1,10)
print(np.unique(a,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))
